### ISSUE TITLE
support not needing an emoji for custom commit types

### ISSUE THREAD

**Issue by its-danny** [cococonscious/koji#13]
atm a custom commit type looks like this:

```toml
[[commit_types]]
name = "feat"
emoji = "✨"
description = "A new feature"
```

it should support not having the `emoji` line, since not everyone wants emoji in their commit messages.
