### ISSUE TITLE
Skip some questions

### ISSUE THREAD

**Issue by 5ouma** [cococonscious/koji#78]
**Is your feature request related to a problem? Please describe.**
I don't write breaking changes and issues, so I want it not to ask me for them.

**Describe the solution you'd like**
Set on the config file like this.
```toml
breaking_change = false
issues = false
```

**Describe alternatives you've considered**
Pass these options to ignore them.
```shell
koji --no-breaking-change --no-issues
```
